<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

namespace GPBMetadata;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac010a0c636f6e6669672e70726f746f1206636f6e66696722200a0d43" .
            "6f6e66696752657175657374120f0a0770726f66696c6518012001280922" .
            "250a0e436f6e666967526573706f6e736512130a0b6a736f6e5f636f6e66" .
            "696718012001280932430a0b436f6e66696753746f726512340a03476574" .
            "12152e636f6e6669672e436f6e666967526571756573741a162e636f6e66" .
            "69672e436f6e666967526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

