<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

namespace Config;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 응답
 *
 * Generated from protobuf message <code>config.ConfigResponse</code>
 */
class ConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string json_config = 1;</code>
     */
    protected $json_config = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $json_config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string json_config = 1;</code>
     * @return string
     */
    public function getJsonConfig()
    {
        return $this->json_config;
    }

    /**
     * Generated from protobuf field <code>string json_config = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonConfig($var)
    {
        GPBUtil::checkString($var, True);
        $this->json_config = $var;

        return $this;
    }

}

